spring.application.name=QRCodeGenerator
spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD


cloud.name=YOUR_CLOUD_NAME
cloud.key=YOUR_API_KEY
cloud.secret=YOUR_API_SECRET
jwt.secret=YOUR_JWT_SECRET
spring.profiles.active=local